// src/contexts/ProductContext.tsx
"use client";

import type { Product } from '@/lib/types';
import { createContext, useContext, ReactNode, useCallback } from 'react';
import { useLocalStorage } from '@/hooks/useLocalStorage';
import { LOCALSTORAGE_KEYS, INITIAL_PRODUCTS } from '@/lib/constants';
import { useToast } from '@/hooks/use-toast';

type ProductUpdatePayload = Partial<Pick<Product, "name" | "price" | "quantity" | "imageUrl" | "barcodeValue">>;

interface ProductContextType {
  products: Product[];
  addProduct: (productData: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>) => Promise<Product | null>;
  updateProduct: (productId: string, updates: ProductUpdatePayload) => Promise<Product | null>;
  deleteProduct: (productId: string) => Promise<boolean>;
  getProductById: (productId: string) => Product | undefined;
  getProductByBarcode: (barcodeValue: string) => Product | undefined; // New method
  updateProductQuantity: (productId: string, quantityChange: number) => Promise<boolean>;
}

const ProductContext = createContext<ProductContextType | undefined>(undefined);

export const ProductProvider = ({ children }: { children: ReactNode }) => {
  const initialProductsCreator = useCallback(() => INITIAL_PRODUCTS, []);
  const [products, setProducts] = useLocalStorage<Product[]>(LOCALSTORAGE_KEYS.PRODUCTS, initialProductsCreator);
  const { toast } = useToast();

  const addProduct = async (productData: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>): Promise<Product | null> => {
    const currentProducts = products || [];
    if (currentProducts.find(p => p.name.trim().toLowerCase() === productData.name.trim().toLowerCase())) {
      toast({ title: "خطأ", description: "منتج بنفس الاسم موجود بالفعل.", variant: "destructive" });
      return null;
    }
    
    const productIdTimestamp = Date.now();
    const generatedProductId = `prod_${productIdTimestamp}`;
    
    const autoGeneratedBarcodeValue = productData.barcodeValue && productData.barcodeValue.trim() !== '' 
      ? productData.barcodeValue.trim() 
      : String(productIdTimestamp);

    const newProduct: Product = {
      ...productData,
      id: generatedProductId,
      imageUrl: productData.imageUrl || '',
      barcodeValue: autoGeneratedBarcodeValue,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    setProducts(prevProducts => [...(prevProducts || []), newProduct]);
    toast({ title: "نجاح", description: `تمت إضافة المنتج "${newProduct.name}" بنجاح.` });
    return newProduct;
  };

  const updateProduct = async (productId: string, updates: ProductUpdatePayload): Promise<Product | null> => {
    let updatedProduct: Product | null = null;
    let hasConflict = false;
    const currentProducts = products || [];

    setProducts(prevProducts =>
      (prevProducts || []).map(p => {
        if (p.id === productId) {
          if (updates.name && updates.name !== p.name && currentProducts.some(op => op.id !== productId && op.name.trim().toLowerCase() === updates.name!.trim().toLowerCase())) {
             toast({ title: "خطأ", description: "منتج آخر بنفس الاسم الجديد موجود بالفعل.", variant: "destructive" });
             hasConflict = true;
             updatedProduct = p; 
             return p; 
          }
          updatedProduct = { ...p, ...updates, updatedAt: new Date().toISOString() };
          return updatedProduct;
        }
        return p;
      })
    );

    if (hasConflict) {
        return updatedProduct; 
    }

    if (updatedProduct && updatedProduct.id === productId) {
        const originalProduct = currentProducts.find(p=> p.id === productId);
        if (JSON.stringify(originalProduct) !== JSON.stringify(updatedProduct)) {
            toast({ title: "نجاح", description: `تم تحديث المنتج "${updatedProduct.name}".` });
        }
    }
    return updatedProduct;
  };

  const deleteProduct = async (productId: string): Promise<boolean> => {
    const currentProducts = products || [];
    const productToDelete = currentProducts.find(p => p.id === productId);
    if (!productToDelete) {
      toast({ title: "خطأ", description: "المنتج غير موجود.", variant: "destructive" });
      return false;
    }
    setProducts(prevProducts => (prevProducts || []).filter(p => p.id !== productId));
    return true;
  };

  const getProductById = (productId: string): Product | undefined => {
    return (products || []).find(p => p.id === productId);
  };

  const getProductByBarcode = (barcodeValue: string): Product | undefined => {
    return (products || []).find(p => p.barcodeValue === barcodeValue);
  };

  const updateProductQuantity = async (productId: string, quantityChange: number): Promise<boolean> => {
    const product = getProductById(productId);
    if (!product) {
      toast({ title: "خطأ", description: "المنتج غير موجود.", variant: "destructive" });
      return false;
    }
    const newQuantity = product.quantity + quantityChange;
    if (newQuantity < 0) {
      toast({ title: "خطأ", description: `لا توجد كمية كافية من المنتج "${product.name}". الكمية المتوفرة: ${product.quantity}`, variant: "destructive" });
      return false;
    }
    
    await updateProduct(productId, { quantity: newQuantity } as ProductUpdatePayload);
    return true;
  };

  return (
    <ProductContext.Provider value={{ products: products || [], addProduct, updateProduct, deleteProduct, getProductById, getProductByBarcode, updateProductQuantity }}>
      {children}
    </ProductContext.Provider>
  );
};

export const useProducts = () => {
  const context = useContext(ProductContext);
  if (context === undefined) {
    throw new Error('useProducts must be used within a ProductProvider');
  }
  return context;
};
